//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTL_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImportBill
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ImportBill()
        {
            this.ImportBillDetail = new HashSet<ImportBillDetail>();
        }
    
        public int ImportBillId { get; set; }
        public int Supplierid { get; set; }
        public int UserId { get; set; }
        public Nullable<System.DateTime> ImportDate { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImportBillDetail> ImportBillDetail { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual Users Users { get; set; }
    }
}
