//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTL_MVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;

    public partial class News
    {
        public int NewsId { get; set; }
        public string Title { get; set; }
        [AllowHtml]
        public string Content { get; set; }
        public Nullable<System.DateTime> DateSubmitted { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<bool> Status { get; set; }
        public string Image { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
